#!/bin/bash
function exists {
  if test -a $1; then
    symbolicLink $1
    kind $1
    owned $1 
  else
    echo $1 nicht gefunden
  fi
}

function kind {
  if test -d $1; then
    echo $1 is a directory
  elif test -f $1; then
    echo $1 is a file
  else
    echo Oops something went wrong
  fi
}

function symbolicLink {
  if test -h $1; then
    echo $1 is a symbolic Link
  else
    echo $1 is not a symbolic link
  fi
}

function owned {
  if test -O $1; then
    echo You are the Owner of $1
  else
    echo You are not the owner
    realOwner $1
  fi
}

function realOwner {
  echo -n "The Owner is: "
  stat -c '%U' $1

}

for param in $@
do
  exists $param
  echo
done
